VKTokenFile: "$HOME/interLink/token"
InterlinkURL: "http://localhost"
SidecarURL: "http://localhost"
InterlinkPort: "30002"
SidecarService: "htcondor" #docker, slurm
SidecarPort: "8000" #docker, slurm
SbatchPath: "/usr/bin/sbatch"
ScancelPath: "/usr/bin/scancel"
CommandPrefix: ""
ExportPodData: true
DataRootFolder: ".knoc/" #".knoc/"
ServiceAccount: "knoc"
Namespace: "vk"
Tsocks: false
TsocksPath: "$WORK/tsocks-1.8beta5+ds1/libtsocks.so"
TsocksLoginNode: "login01"
